plugins:
  layouts_topic_lists:
    client: true
    type: list
    default: 'latest'
    choices:
      - latest
      - new
      - unread
      - top
      - bookmarks
  layouts_topic_lists_limit: 10
